// React/src/App.js
import React from "react";
import 'devexpress-diagram/dist/dx-diagram.min.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import ArrayStore from "devextreme/data/array_store";
import Diagram, { Nodes, DefaultItemProperties, Toolbox, PropertiesPanel, Tab, Group } from 'devextreme-react/diagram';
import service from './data.js';

const dataSource = new ArrayStore({
  key: 'ID',
  data: service.getTasks(),
});
const objectCommands = ['lineStyle', 'lineColor', 'fillColor'];
const toolboxShapes = ['text', 'rectangle'];
function App() {
  return (
    <Diagram
      simpleView={true}
      pageColor="#f0f0f0"
    >
      <Nodes
        dataSource={dataSource}
        keyExpr="ID"
        textExpr="Task_Name"
        parentKeyExpr="Parent_ID"
      />
      <DefaultItemProperties
        textStyle="font-family: 'Courier New', monospace;"
      />
      <PropertiesPanel>
        <Tab>
          <Group
            title="Object Properties"
            commands={objectCommands}
          />
        </Tab>
      </PropertiesPanel>
      <Toolbox showSearch={false} >
        <Group
          category="general"
          shapes={toolboxShapes}
        />
      </Toolbox>
    </Diagram>
  );
};

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AppService, Task } from './app.service';
import ArrayStore from 'devextreme/data/array_store';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [AppService],
})

export class AppComponent {
  projectTasks: Task[];
  dataSource: ArrayStore;
  constructor(service: AppService) {
    this.projectTasks = service.getTasks();
    this.dataSource = new ArrayStore({
      key: 'ID',
      data: service.getTasks(),
    });
  }
}

<dx-diagram [simpleView]="true" pageColor="#f0f0f0">
  <dxo-nodes [dataSource]="dataSource" keyExpr="ID" parentKeyExpr="Parent_ID" textExpr="Task_Name">
  </dxo-nodes>
  <dxo-default-item-properties textStyle="font-family: 'Courier New', monospace;">
  </dxo-default-item-properties>
  <dxo-properties-panel>
    <dxi-tab>
      <dxi-group title="Object Properties" [commands]="['lineStyle', 'lineColor', 'fillColor']"></dxi-group>
    </dxi-tab>
  </dxo-properties-panel>
  <dxo-toolbox [showSearch]="false">
    <dxi-group category="general" [shapes]="['text', 'rectangle']"></dxi-group>
  </dxo-toolbox>
</dx-diagram>
